Repository BrettMayson/HEMTT, pull requests merged in 2019-02, with the labels that each got.

#21 semver build on ci
  .travis.yml
  Cargo.lock
  appveyor.yml
  ci/version.ps1
  ci/version.sh
Labels: ci

#23 Optional Addons
  Cargo.lock
  docs/json.md
  docs/usage.md
  src/build.rs
  src/main.rs
  src/project.rs
Labels: enhancement, hemtt.json

#12 Check include folders and expose to configuration
  docs/getting_started.md
  docs/json.md
  src/build.rs
  src/project.rs
Labels: bug, enhancement, hemtt.json

#33 Build Feature - change --opts, add --skip
  docs/json.md
  docs/usage.md
  src/build.rs
  src/main.rs
  src/project.rs
Labels: enhancement

#35 Build Feature - Build specific addons
  docs/usage.md
  src/build.rs
  src/files.rs
  src/main.rs
Labels: enhancement
