Repository BrettMayson/HEMTT, pull requests merged in 2019-04, with the labels that each got.

#9 Utility: release build archiving (zip)
  Cargo.lock
  Cargo.toml
  docs/utilities.md
  src/build/script.rs
  src/main.rs
  src/utilities/mod.rs
  src/utilities/zip.rs
Labels: utility

#85 Extend files configuration
  Cargo.lock
  Cargo.toml
  docs/project.md
  src/build/release.rs
Labels: bug, enhancement

#89 Look upwards for HEMTT project file
  src/main.rs
  src/project.rs
  src/utilities/convert.rs
  src/utilities/translation.rs
Labels: enhancement

#92 SemVer templating
  docs/templating.md
  docs/utilities.md
  src/build/script.rs
  src/main.rs
  src/project.rs
  src/template.rs
  src/utilities/mod.rs
  src/utilities/zip.rs
Labels: enhancement, templating

#96 dev builds windows installer
  appveyor.yml
Labels: ci

#97 Fix zip using backslash on Windows
  Cargo.lock
  Cargo.toml
  src/utilities/zip.rs
Labels: bug, external

#51 Don't write private key to disk
  docs/project.md
  rustfmt.toml
  src/build/mod.rs
  src/build/release.rs
  src/build/sign.rs
  src/main.rs
  src/project.rs
Labels: enhancement
