Repository BrettMayson/HEMTT, pull requests merged in 2019-06, with the labels that each got.

#90 Run armake2 through HEMTT
  Cargo.lock
  src/main.rs
  src/utilities/armake.rs
  src/utilities/mod.rs
Labels: utility

#138 Always set current path as first include folder
  src/build/mod.rs
Labels: enhancement

#137 Fix crash when no arguments are provided
  src/main.rs
Labels: bug

#75 Clear keys when clearing releases
  src/build/release.rs
  src/files.rs
  src/main.rs
Labels: enhancement
