Repository BrettMayson/HEMTT, pull requests merged in 2019-03, with the labels that each got.

#49 Build Steps
  Cargo.lock
  Cargo.toml
  src/build/mod.rs
  src/build/result.rs
  src/build/script.rs
  src/main.rs
  src/project.rs
  src/state.rs
  src/utilities/mod.rs
  src/utilities/translation.rs
Labels: wip

#52 Convert
  docs/utilities.md
  src/project.rs
  src/utilities/convert.rs
  src/utilities/mod.rs
Labels: utility

#60 Windows Installer
  Cargo.toml
  appveyor.yml
  ci/before_deploy.ps1
  ci/wininstaller.iss
Labels: ci, wip

#70 Fix sign pbo file prefix check
  src/build/sign.rs
Labels: bug
